{
 "title": "Apache Artemis local Overview",
 "description": "Dashboard for monitoring Apache Artemis",
 "tags": [
  "PRO",
  "apache artemis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_info, instance)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "artemis_uptime_millis{ job=\"artemis\"} / 1000 / 60"
    }
   ]
  },
  {
   "title": "Started",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "artemis_started{ job=\"artemis\"}"
    }
   ]
  },
  {
   "title": "Messages Count ALL BROKERS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_message_count{job=\"artemis\",queue!~\"\"}",
     "legendFormat": "Broker: {{instance}} Queue: {{ queue }}"
    }
   ]
  },
  {
   "title": "Messages added ALL BROKERS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_messages_added{job=\"artemis\"}",
     "legendFormat": "Broker: {{instance}} Queue: {{ queue }}"
    }
   ]
  },
  {
   "title": "Ack attempts  ALL BROKERS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_acknowledge_attempts{job=\"artemis\"}",
     "legendFormat": "Broker: {{instance}} Queue: {{ queue }}"
    }
   ]
  },
  {
   "title": "Routed messages ALL BROKERS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_routed_message_count{job=\"artemis\"}",
     "legendFormat": "Broker: {{instance}} Queue: {{ queue }}"
    }
   ]
  },
  {
   "title": "Connections and Consumers ALL Brokers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_connection_count{ job=\"artemis\"}",
     "legendFormat": "Connection Count {{instance}}"
    },
    {
     "expr": "artemis_consumer_count{ job=\"artemis\"}",
     "legendFormat": "{{ address }}  {{instance}}"
    }
   ]
  },
  {
   "title": "Address Paging",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "artemis_paging{job=\"artemis\"}"
    }
   ]
  },
  {
   "title": "Address Paging State-Fluctuation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "artemis_paging{job=\"artemis\"}"
    }
   ]
  },
  {
   "title": "Artemis Address Size ALL BROKERS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "artemis_address_size{job=\"artemis\"}",
     "legendFormat": "{{ address }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Message Count $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_message_count{instance=\"$instance\", job=\"artemis\"}",
     "legendFormat": "Address: {{ address }} Queue: {{ queue }}"
    }
   ]
  },
  {
   "title": "JMV Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$instance\",job=\"artemis\"}",
     "legendFormat": "{{ area }} "
    }
   ]
  },
  {
   "title": "JMV Memory Pool Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\",job=\"artemis\"}",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "JMV GC Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=\"$instance\",job=\"artemis\"}",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  {
   "title": "JMV Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\",job=\"artemis\"}",
     "legendFormat": "current {{ instance }}"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\",job=\"artemis\"}",
     "legendFormat": "peak {{ instance }}"
    }
   ]
  }
 ]
}